### ISSUE TITLE
Not able to activate after Install

### ISSUE THREAD

**Issue by kumarapush** [wpmudev/coursepress#1]
I keep getting this message when I try to activate coursepress in my wordpress site. 
Error message - "There was an issue determining where CoursePress Pro is installed. Please reinstall it."

Please help.

**Comment by Fro8888** [comment]
I'm in the same boat as well! I tried installing it on an older WordPress version to see if that was the issue and that did nothing. I tried researching a solution for 3 hours and came up with no solutions...

**Comment by ivan-ivanic-cm** [comment]
Checkout `development` branch, read README file, there are instructions on how to package using npm/grunt.

**Comment by cuppajoey** [comment]
I ran into this issue as well. I think the problem is that a direct download from Github names the plugin directory as 'coursepress-master' but the main plugin class defines the directory as 'coursepress'. 

I just renamed the plugin directory from 'coursepress-master' to 'coursepress' and it worked fine for me. Hope that helps.

**Comment by renaudham** [comment]
agree with cuppajoey, changing folder name is ok
But then there is also a bug in the url just after
http://coursepress2020.com/wp-admin/admin.php?page = courses&quick_setup
should be with no space
http://coursepress2020.com/wp-admin/admin.php?page=courses&quick_setup

**Comment by renaudham** [comment]
anyway..
Current version is old and not adapted to newer WP, Php version and JQuery.
Not working as it is, at all

In case somebody is interested, I started slowly and consider updating all this to make it work, then later adding new addons and updates.. 
Also probably fixing MarketPress to be able to sell courses..

**Comment by Dapjosh** [comment]
> anyway..
> Current version is old and not adapted to newer WP, Php version and JQuery.
> Not working as it is, at all
> 
> In case somebody is interested, I started slowly and consider updating all this to make it work, then later adding new addons and updates..
> Also probably fixing MarketPress to be able to sell courses..

I am interested in this. I have also tried making some updates from my end but it is overwhelming.

**Comment by louptn** [comment]
> anyway..
> Current version is old and not adapted to newer WP, Php version and JQuery.
> Not working as it is, at all
> 
> In case somebody is interested, I started slowly and consider updating all this to make it work, then later adding new addons and updates..
> Also probably fixing MarketPress to be able to sell courses..

Interested too...
